items:
  - name: Online
    slug: online
    href: '#Online'
    description: Relays where a connection can currently be established. 
  - name: Public
    slug: public
    href: '#public'
    description: Public relays are relays where anyone can read or write. 
  - name: Paid
    slug: paid
    href: '#paid'
    description: Relays that use a payment model to mitigate spam.
  - name: Offline
    slug: offline
    href: '#offline'
    description: Relays where a connection cannot currently be established
  - name: All
    slug: all
    href: '#all'
    description: All relays ordered by latency
  - name: Favorites
    slug: favorite
    href: '#favorite'
    condition: auth
    description: Relays you have favorited